### ISSUE TITLE
Dependency on Test::HexString not declared

### ISSUE THREAD

**Issue by andk** [team-at-cpan/Net-Async-Redis#1]
As per subject. Grep: http://search.cpan.org/grep?release=Net-Async-Redis-1.000;string=Test::HexString;n=1;C=0

Sample fail report: http://www.cpantesters.org/cpan/report/89951080

Thanks,

**Comment by tm604** [comment]
This was fixed in 0f6c4ce0d6ab657420ca418938c10f8592fee142 - thanks!
