### ISSUE TITLE
Pipelined commands not RESP encoded

### ISSUE THREAD

**Issue by dankroboth** [team-at-cpan/Net-Async-Redis#14]
It appears there issue with how the pipelined commands are handled [here](https://metacpan.org/release/Net-Async-Redis/source/lib/Net/Async/Redis.pm#L678)

The $cmd variable is just a space joined version of the arguments, and not the RESP encoded version.  Therefore, when the command is retrieved [here](https://metacpan.org/release/Net-Async-Redis/source/lib/Net/Async/Redis.pm#L500), the Redis server rejects them because they are not encoded in RESP.

**Comment by tm604** [comment]
Thanks - yes, that does not sound good at all. Currently working on some test cases for this, will release a new version as soon as there's a fix and some proper coverage here.

**Comment by tm604** [comment]
Should be resolved in 2.005, thanks!

**Comment by dankroboth** [comment]
> Should be resolved in 2.005, thanks!

Thank you @tm604 !
