### ISSUE TITLE
Can't authenticate with Cloud Providers like Aiven.io

### ISSUE THREAD

**Issue by pnevins** [team-at-cpan/Net-Async-Redis#30]
When trying to use a Redis Cloud provider like Aiven.io, I'm not able to authenticate with the following example due to mutations to the URI.  Please note that Aiven.io requires and extra "s" for the "rediss://" start of the URI.

When tracing out the URI of `"rediss://username:password@demo-1.aivencloud.com:16031"` was changed to `"redis://rediss:6379//username:password@demo-1.aivencloud.com:16031"`

Also, the authentication parameters also have the username removed before trying to authenticate.  This makes using ACL authentication not possible.

Example Code:

```use strict;
use warnings;
use Future::AsyncAwait;
use IO::Async::Loop;
use Net::Async::Redis;

my $redis = Net::Async::Redis->new(
        uri => 'rediss://username:password@demo-1.aivencloud.com:16031'
);

$loop->add($redis);
$redis->connect()->then(sub {
    print("#connected! \n");
})->on_fail(sub {
    my $error = shift;
    print("Redis connection error : $error \n");
})->get;

**Comment by tm604** [comment]
Thanks for the report - you're right, `rediss` secure URIs are not handled correctly.

I'll add support for those, although it'd need the certificates as well (as extra parameters to `->new` or `->configure`).

`username` passthrough is also worth adding.

**Comment by tm604** [comment]
Cleaning up - this should be in place in the current 4.002 version on CPAN, now that https://github.com/team-at-cpan/Net-Async-Redis/commit/a5982efdcbf0700c93b4c0759dfcdd595843e553 and https://github.com/team-at-cpan/Net-Async-Redis/commit/8ee13c35cd887877f5b8961433b4327c866d3f9f are in place. Thanks!
