### ISSUE TITLE
Using a URI without `redis://...` fails

### ISSUE THREAD

**Issue by leonerd** [team-at-cpan/Net-Async-Redis#7]
If the URI does not have the `redis://...` scheme, then code later fails:

    Can't locate object method "userinfo" via package "URI::_generic" at .../lib/perl5/Net/Async/Redis.pm line 250.

A quite simple fix for this is something like

    $uri = "redis://$uri" unless $uri =~ m{^redis://};

Or maybe have the URI checked/rejected by the configure method?

**Comment by tm604** [comment]
Should now be supported in 2.005, thanks!
